config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :post
  validates :post, presence: true
  validates :first_name, presence: true, uniqueness: {scope: [:last_name, :second_name], case_sensitive: false}
  validates :last_name, presence: true, length: {maximum: 128, minimum: 2}
  validates :birthday, presence: true
  validates :sex, length: {is: 1}, inclusion: {in: ['м' ,'ж'], message: "введенное значение должно быть м или ж" }

end

app/models/post.rb
class Post < ApplicationRecord
	has_many :people
	validates :name, presence: true, length: {maximum: 256} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :second_name, :birthday, :sex, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Our Logo</a>
  <form class="form-inline">
    <a class="btn btn-outline-primary" href="/people" role="button">People</a>
<!--     <span class="btn btn-outline-primary" role="button">
    <%= link_to 'People', (url_for(controller: 'people', action: 'index'))%>    
    </span> -->
    <div style="padding-left: 10px;">
      <a class="btn btn-outline-success" href="/posts" role="button">Posts</a>
<!--       <span class="btn btn-outline-success" role="button">
      <%= link_to 'Posts', (url_for(controller: 'posts', action: 'index'))%>
      </span> -->
    </div>
  </form>
</nav>

app/views/application/_navbar_top_html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Our Logo</a>
  <form class="form-inline">
    <a class="btn btn-outline-primary" href="people/index" role="button">
    Login
    </a>
    <div style="padding-left: 10px;">
      <a class="btn btn-outline-success" href="posts/index" role="button">
      Sign Up
      </a>
    </div>
  </form>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Our Logo</a>
  <form class="form-inline">
    <a class="btn btn-outline-primary" href="people/index" role="button">
    Login
    </a>
    <div style="padding-left: 10px;">
      <a class="btn btn-outline-success" href="posts/index" role="button">
      Sign Up
      </a>
    </div>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>

    <%= render "application/nav" %>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_area :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_area :last_name %>
  </div>

  <div class="field">
    <%= form.label :second_name %>
    <%= form.text_area :second_name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_area :sex %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table class = "table table-hover">
  <thead>
    <tr>
      <th><%= Person.human_attribute_name(:first_name) %></th>
      <th><%= Person.human_attribute_name(:last_name) %></th>
      <th><%= Person.human_attribute_name(:second_name) %></th>
      <th><%= Person.human_attribute_name(:birthday) %></th>
      <th><%= Person.human_attribute_name(:sex) %></th>
      <th><%= Person.human_attribute_name(:post) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.second_name %></td>
        <td><%= person.birthday %></td>
        <td><%= person.sex %></td>
        <td><%= person.post.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a type="button" class="btn btn-info" href="/people/new">New person</a>
<!-- <button type="button" class="btn btn-info"><%= link_to 'New Person', new_person_path %></button>
 -->  

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @person.second_name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @person.sex %>
</p>

<p>
  <strong>Post:</strong>
  <%= @person.post_id %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>